// NAPCS Unionization Research Project | PLT Strategies Group, Inc.
// Auto-generated by build_regional_schools.js — do not edit manually.
// Source: Charter_School_Registry_v67.xlsx
// Generated: 2026-05-28
//
// Region: TX | States: TX
// Records: 0 | Status: {}

var NAPCS_SCHOOLS_TX = [];
